### PR TITLE
Update anaconda installation instructions

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Review by vuillaut — COMMENTED** [review]
Hi.
You probably know more than me but:
- why ```Choose the install location, we recommend `~/.local/anaconda3` instead of `~/anaconda3` to not mess up you home too much.``` ?
- why not using a simpler (?) script as done previously to do the config?

**Comment by maxnoe** [comment]
> why Choose the install location, we recommend `~/.local/anaconda3` instead of `~/anaconda3` to not mess up you home too much. ?

Just personal preference. I don't like having software in the root of my home. `.local` is the canonical place and keeps clutter from the home.

>   why not using a simpler (?) script as done previously to do the config?

What is more simple than typing `conda activate` and `conda deactivate`?
Why develop our own, unsupported script, if anaconda provides the `conda.sh` script?

**Comment by maxnoe** [comment]
For the `conda.sh` stuff, please see: https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/

It explains, why it is not recommended anymore to add `anaconda/bin` to the `PATH` and use the `conda.sh` script instead.

**Comment by maxnoe** [comment]
As the school is coming up, do you think we can merge this? Or do you disagree on something?

**Pull request merged**
